Views/Home/Contact.cshtml

Hello Sebastian
please review
H.

changed marketing and support emails

---

TOZ_dotnet/Toz.Dotnet.Models/EnumTypes/PetSex.cs
TOZ_dotnet/Toz.Dotnet.Models/EnumTypes/PetType.cs
TOZ_dotnet/Toz.Dotnet.Models/Pet.cs
TOZ_dotnet/Toz.Dotnet.Models/Toz.Dotnet.Models.csproj

- Pet.cs - model zwierzaka
- PetSex.cs - plec zwierzaka
- PetType.cs - rodzaj zwierzaka (pies lub kot)

Nowe pliki:

---

Toz.Dotnet/Toz.Dotnet.Core/Interfaces/IPetsManagementService.cs
Toz.Dotnet/Toz.Dotnet.Core/Services/PetsManagementService.cs
Toz.Dotnet/Toz.Dotnet.Models/Pet.cs
Toz.Dotnet/Toz.Dotnet.Tests/Tests/PetsManagementTest.cs
Toz.Dotnet/Toz.Dotnet/Views/Pets/Index.cshtml

- Added methods to the PetsManagementService
- Added unit tests for PetsManagementService
Tests included, are not the finish ones and will be replaced as soon as we'll know how does the backend want to perform their functionalities. For now test are only for beeing

Added methods and unit tests to the PetsManagementService

---

Toz.Dotnet/Toz.Dotnet/Resources/Views.Pets.Add.en-US.resx
Toz.Dotnet/Toz.Dotnet/Resources/Views.Pets.Index.pl.resx
Toz.Dotnet/Toz.Dotnet/Resources/Views.Shared._Layout.de.resx
Toz.Dotnet/Toz.Dotnet/Resources/Views.Shared._Layout.en-US.resx
Toz.Dotnet/Toz.Dotnet/Resources/Views.Shared._Layout.pl.resx
Toz.Dotnet/Toz.Dotnet/Views/Pets/Add.cshtml
Toz.Dotnet/Toz.Dotnet/Views/Pets/Edit.cshtml
Toz.Dotnet/Toz.Dotnet/Views/Shared/_Layout.cshtml
Toz.Dotnet/Toz.Dotnet/wwwroot/css/site.css
Toz.Dotnet/Toz.Dotnet/wwwroot/css/site.min.css
Toz.Dotnet/Toz.Dotnet/wwwroot/css/style.css

Cleaned up CSS files a bit
Fixed typos etc
Some little changes in design

Description is now a textarea

---

Toz.Dotnet/Toz.Dotnet.Tests/Tests/PetsManagementTest.cs
Toz.Dotnet/Toz.Dotnet.Tests/Toz.Dotnet.Tests.csproj
Toz.Dotnet/Toz.Dotnet/Controllers/PetsController.cs
Toz.Dotnet/Toz.Dotnet/Properties/launchSettings.json
Toz.Dotnet/Toz.Dotnet/Views/Pets/Add.cshtml
Toz.Dotnet/Toz.Dotnet/Views/Pets/Edit.cshtml
Toz.Dotnet/Toz.Dotnet/wwwroot/css/site.css
Toz.Dotnet/Toz.Dotnet/wwwroot/css/site.min.css

I built on version 1.0.0-preview4-004233.

Added data validation to edit procedure.

---

Toz.Dotnet/Toz.Dotnet.Core/Interfaces/IPetsManagementService.cs
Toz.Dotnet/Toz.Dotnet.Core/Services/PetsManagementService.cs
Toz.Dotnet/Toz.Dotnet/Congfiguration/AppSettings.cs
Toz.Dotnet/Toz.Dotnet/Controllers/PetsController.cs
Toz.Dotnet/Toz.Dotnet/Resources/Views.Pets.Add.de.resx
Toz.Dotnet/Toz.Dotnet/Resources/Views.Pets.Add.en-US.resx
Toz.Dotnet/Toz.Dotnet/Resources/Views.Pets.Add.pl.resx
Toz.Dotnet/Toz.Dotnet/Resources/Views.Pets.Edit.de.resx
Toz.Dotnet/Toz.Dotnet/Resources/Views.Pets.Edit.en-US.resx
Toz.Dotnet/Toz.Dotnet/Resources/Views.Pets.Edit.pl.resx
Toz.Dotnet/Toz.Dotnet/Startup.cs
Toz.Dotnet/Toz.Dotnet/Views/Pets/Add.cshtml
Toz.Dotnet/Toz.Dotnet/Views/Pets/Edit.cshtml
Toz.Dotnet/Toz.Dotnet/Views/Pets/Index.cshtml
Toz.Dotnet/Toz.Dotnet/appsettings.json

Add AppSettings.cs
Edit appsettings.json.
Add custom configuration in Startup.cs (AppSettings.cs and appsettings.json)
Edit View.Add and View.Edit for upload and validation.
Add ConvertPhotoToByteArray() in PetsManagementService.
Add "photo alerts" in Resources (Add and Edit).
Add validation photo in PetsController (function: Add, Edit).

Upload and validation photo

---

Toz.Dotnet/Toz.Dotnet.Models/Pet.cs
Toz.Dotnet/Toz.Dotnet/Views/Pets/Add.cshtml
Toz.Dotnet/Toz.Dotnet/Views/Pets/Edit.cshtml
Toz.Dotnet/Toz.Dotnet/wwwroot/css/site.css
Toz.Dotnet/Toz.Dotnet/wwwroot/css/site.min.css

Changes:
- removed redundant validation (not defined in the Story)
- error messages displayed above inputs
- different styling of incorrect filled input (background, border)

Removed redundant validation, validation error styling.

---

Toz.Dotnet/Toz.Dotnet.Models/EnumTypes/NewsStatus.cs
Toz.Dotnet/Toz.Dotnet.Models/News.cs
Toz.Dotnet/Toz.Dotnet.Models/Pet.cs
Toz.Dotnet/Toz.Dotnet.Resources/ModelsDataValidation.Designer.cs
Toz.Dotnet/Toz.Dotnet.Resources/ModelsDataValidation.de.resx
Toz.Dotnet/Toz.Dotnet.Resources/ModelsDataValidation.en.resx
Toz.Dotnet/Toz.Dotnet.Resources/ModelsDataValidation.pl.resx
Toz.Dotnet/Toz.Dotnet.Resources/ModelsDataValidation.resx
Toz.Dotnet/Toz.Dotnet.Resources/Toz.Dotnet.Resources.csproj

News model

---

Toz.Dotnet/Toz.Dotnet.Core/Interfaces/IPetsManagementService.cs
Toz.Dotnet/Toz.Dotnet.Core/Interfaces/IRestService.cs
Toz.Dotnet/Toz.Dotnet.Core/Services/PetsManagementService.cs
Toz.Dotnet/Toz.Dotnet.Core/Services/RestService.cs
Toz.Dotnet/Toz.Dotnet.Models/JsonConventers/JsonDateTimeConventer.cs
Toz.Dotnet/Toz.Dotnet/Controllers/PetsController.cs

- Async actions in PetsController
- Cancelation tokens in PetsService

Luse/tozpatron 00/async controllers actions

---

Toz.Dotnet/Toz.Dotnet/Controllers/PetsController.cs
Toz.Dotnet/Toz.Dotnet/Resources/Views.Pets.Add.de.resx
Toz.Dotnet/Toz.Dotnet/Resources/Views.Pets.Add.en-US.resx
Toz.Dotnet/Toz.Dotnet/Resources/Views.Pets.Add.pl.resx
Toz.Dotnet/Toz.Dotnet/Resources/Views.Pets.Edit.de.resx
Toz.Dotnet/Toz.Dotnet/Resources/Views.Pets.Edit.en-US.resx
Toz.Dotnet/Toz.Dotnet/Resources/Views.Pets.Edit.pl.resx
Toz.Dotnet/Toz.Dotnet/Views/Pets/Add.cshtml
Toz.Dotnet/Toz.Dotnet/Views/Pets/Edit.cshtml
Toz.Dotnet/Toz.Dotnet/wwwroot/css/site.css

Change Add and Edit View and function in PetController.
Change ValidatePhoto function in PetController.
Add new data in Resources.
Add support white-space for field-validation-error in site.css.

Fix add pet without photo

---

Toz.Dotnet/Toz.Dotnet/Resources/Views.News.Add.de.resx
Toz.Dotnet/Toz.Dotnet/Resources/Views.News.Add.en.resx
Toz.Dotnet/Toz.Dotnet/Resources/Views.News.Add.pl.resx
Toz.Dotnet/Toz.Dotnet/Resources/Views.News.Edit.de.resx
Toz.Dotnet/Toz.Dotnet/Resources/Views.News.Edit.en.resx
Toz.Dotnet/Toz.Dotnet/Resources/Views.News.Edit.pl.resx
Toz.Dotnet/Toz.Dotnet/Views/News/Add.cshtml
Toz.Dotnet/Toz.Dotnet/Views/News/Details.cshtml
Toz.Dotnet/Toz.Dotnet/Views/News/Edit.cshtml

I pulled from master branch once again and made changes as follows:
- created forms for Adding and Editing News
- modified Details View
- added new translations

NewsAddAndEdit:

---

Toz.Dotnet/Toz.Dotnet.Tests/Tests/NewsManagmentTest.cs
Toz.Dotnet/Toz.Dotnet.Tests/Tests/PetsManagmentTest.cs
Toz.Dotnet/Toz.Dotnet.Tests/Tests/UsersManagementServiceTest.cs

- fixed building issues
- commented out UsersManagmentServices tests for now

Test fixes

---

Toz.Dotnet/Toz.Dotnet.Core/Services/PetsManagementService.cs
Toz.Dotnet/Toz.Dotnet.Core/Services/UsersManagementService.cs
Toz.Dotnet/Toz.Dotnet.Resources/CustomValidationAttributes/PhoneNumberAttribute.cs
Toz.Dotnet/Toz.Dotnet/Controllers/UsersController.cs
Toz.Dotnet/Toz.Dotnet/Startup.cs
Toz.Dotnet/Toz.Dotnet/Views/Users/Index.cshtml

1. Added fully functional Controller & DI setup for that controller. User creation flow is now possible to present.
2. Modified Index razor view to display a list of users.
3. Fixed Phone Number validation.
4. Fixed UsersManagementService constructor to prevent circular reference.
5. (minor) Sorted usings in PetManagementService
6. Fixed unit tests for UserManagementService

UserController

---

Toz.Dotnet/Toz.Dotnet.Models/Config.cs
Toz.Dotnet/Toz.Dotnet.Models/News.cs
Toz.Dotnet/Toz.Dotnet.Models/Period.cs
Toz.Dotnet/Toz.Dotnet.Models/Pet.cs
Toz.Dotnet/Toz.Dotnet.Models/Reservartion.cs
Toz.Dotnet/Toz.Dotnet.Models/Reservation.cs
Toz.Dotnet/Toz.Dotnet.Models/Schedule.cs
Toz.Dotnet/Toz.Dotnet.Models/User.cs

backend models for mapping data form its API

Luse/tozpatron 204/schedule models

---

Toz.Dotnet/Toz.Dotnet.Models/EnumTypes/UserType.cs
Toz.Dotnet/Toz.Dotnet/Views/Users/Add.cshtml

1. Changed the default user role to Volunteer.
2. Changed order of options for the user type dropdown list in Add.cshtml. Volunteer will be selected by default.

Default user role fix

---

Toz.Dotnet/Toz.Dotnet/Views/Shared/_Layout.cshtml

1. Hidden the culture selectors (flags) on the top bar.

Delocalization

---

Toz.Dotnet/Toz.Dotnet/Resources/Views/Schedule/Index.de.resx
Toz.Dotnet/Toz.Dotnet/Resources/Views/Schedule/Index.en-US.resx
Toz.Dotnet/Toz.Dotnet/Resources/Views/Schedule/Index.pl.resx
Toz.Dotnet/Toz.Dotnet/Views/Schedule/Index.cshtml

1. Added localised slots descriptions
2. Added extra styling

Schedule slots' descriptions

---

Toz.Dotnet/Toz.Dotnet.Core/Interfaces/IOrganizationManagementService.cs
Toz.Dotnet/Toz.Dotnet.Models/Organization.cs
Toz.Dotnet/Toz.Dotnet.Models/OrganizationSubtypes/Contact.cs
Toz.Dotnet/Toz.Dotnet.Resources/Configuration/AppSettings.cs
Toz.Dotnet/Toz.Dotnet.Resources/ModelsDataValidation.Designer.cs
Toz.Dotnet/Toz.Dotnet.Resources/ModelsDataValidation.de.resx
Toz.Dotnet/Toz.Dotnet.Resources/ModelsDataValidation.en.resx
Toz.Dotnet/Toz.Dotnet.Resources/ModelsDataValidation.resx
Toz.Dotnet/Toz.Dotnet/Controllers/OrganizationController.cs
Toz.Dotnet/Toz.Dotnet/Resources/Views/Organization/Info.en-US.resx
Toz.Dotnet/Toz.Dotnet/Resources/Views/Organization/Info.pl.resx
Toz.Dotnet/Toz.Dotnet/Resources/Views/Shared/_Layout.de.resx
Toz.Dotnet/Toz.Dotnet/Resources/Views/Shared/_Layout.pl.resx
Toz.Dotnet/Toz.Dotnet/Startup.cs
Toz.Dotnet/Toz.Dotnet/Views/Organization/Info.cshtml
Toz.Dotnet/Toz.Dotnet/Views/Shared/_Layout.cshtml
Toz.Dotnet/Toz.Dotnet/Views/Users/Add.cshtml
Toz.Dotnet/Toz.Dotnet/appsettings.json

- [Feature]: added view for Organization Info with both read-only and edit mode support.
- [Feature]: added basic controller implementation.
- [Feature]: added IOrganizationManagementService interface for the future service.
- [Feature]: added PL localization strings for the above.
- [Feature]: added backend urls for OrganizationInfo API
- [Feature]: added "Organization Info" button to _Layout.cshtml (top bar)
- [Feature]: added OnlyDigits localization strings to Resources/ModelsDataValidation Designer and resource files.
- [Bug fix]: Add.cshtml -> changed Localizer["Title"] to Localizer["PageTitle"] to match resources string
- [Refactoring]: renamed OrganizationInfo class name & file name to Organization to match backend naming
- [Refactoring]: removed unnecessary usings from …

Organization Info View

---

Toz.Dotnet/Toz.Dotnet.Models/UserBase.cs
Toz.Dotnet/Toz.Dotnet.Models/ViewModels/ReservationToken.cs
Toz.Dotnet/Toz.Dotnet/Views/Users/Add.cshtml

Changed regular expression for user and reservation token
Proper page title while adding an user

Polish Chars

---

Toz.Dotnet/Toz.Dotnet/Controllers/PetsController.cs
Toz.Dotnet/Toz.Dotnet/Views/Pets/Edit.cshtml

We can not remove pets

---

Toz.Dotnet/Toz.Dotnet.Core/Services/AuthService.cs
Toz.Dotnet/Toz.Dotnet.Core/Services/HowToHelpInformationService.cs
Toz.Dotnet/Toz.Dotnet.Core/Services/NewsManagmentService.cs
Toz.Dotnet/Toz.Dotnet.Core/Services/OrganizationManagementService.cs
Toz.Dotnet/Toz.Dotnet.Core/Services/PetsManagementService.cs
Toz.Dotnet/Toz.Dotnet.Core/Services/ProposalsManagementService.cs
Toz.Dotnet/Toz.Dotnet.Core/Services/ScheduleManagementService.cs
Toz.Dotnet/Toz.Dotnet.Core/Services/UsersManagementService.cs
Toz.Dotnet/Toz.Dotnet/appsettings.json

Edit appsettings.json
Edit all services

Change BE path to shorter.

---

Toz.Dotnet/Toz.Dotnet.Tests.Sanity/SanityTests.cs
Toz.Dotnet/Toz.Dotnet.Tests/Helpers/RequestUriHelper.cs
Toz.Dotnet/Toz.Dotnet.Tests/Helpers/TestingObjectProvider.cs
Toz.Dotnet/Toz.Dotnet.Tests/Tests/HelpersManagementTests.cs
Toz.Dotnet/Toz.Dotnet/appsettings.json
Toz.Dotnet/Toz.Dotnet/appsettingsl.json

Tests for helpers management service and model

Luse/tozpatron 00/helpers tests

---

Toz.Dotnet/Toz.Dotnet.Models/Helper.cs
Toz.Dotnet/Toz.Dotnet.Models/Pet.cs
Toz.Dotnet/Toz.Dotnet.Models/ViewModels/PetViewModel.cs
Toz.Dotnet/Toz.Dotnet/Controllers/PetsController.cs
Toz.Dotnet/Toz.Dotnet/Resources/Controllers/PetsController.pl.resx
Toz.Dotnet/Toz.Dotnet/Resources/Views/Pets/Add.en-US.resx
Toz.Dotnet/Toz.Dotnet/Resources/Views/Pets/Add.pl.resx
Toz.Dotnet/Toz.Dotnet/Resources/Views/Pets/Edit.en-US.resx
Toz.Dotnet/Toz.Dotnet/Resources/Views/Pets/Edit.pl.resx
Toz.Dotnet/Toz.Dotnet/Resources/Views/Pets/Index.en-US.resx
Toz.Dotnet/Toz.Dotnet/Resources/Views/Pets/Index.pl.resx
Toz.Dotnet/Toz.Dotnet/Views/Pets/Add.cshtml
Toz.Dotnet/Toz.Dotnet/Views/Pets/Edit.cshtml
Toz.Dotnet/Toz.Dotnet/Views/Pets/Index.cshtml

1. Adjusted Pets views and associated resource files to be in line with recent requirements (epic TOZPATRON-351)
2. Added dropdown list for assigning helper to pets in Pets/Add and Pets/Edit views.
3. Added DisplayedName property in Helper model to make displaying name and address strings for helpers as easy as possible.

Assigning Helpers to Pets

---

.gitignore
Toz.Dotnet/Toz.Dotnet.Core/Interfaces/IAccountManagementService.cs
Toz.Dotnet/Toz.Dotnet.Core/Interfaces/IRestService.cs
Toz.Dotnet/Toz.Dotnet.Core/Services/AccountManagementService.cs
Toz.Dotnet/Toz.Dotnet.Core/Services/RestService.cs
Toz.Dotnet/Toz.Dotnet.Models/ForgotPassword.cs
Toz.Dotnet/Toz.Dotnet.Resources/Configuration/AppSettings.cs
Toz.Dotnet/Toz.Dotnet.Tests.Sanity/SanityTests.cs
Toz.Dotnet/Toz.Dotnet.Tests/Tests/AccountServiceTests.cs
Toz.Dotnet/Toz.Dotnet.Tests/Tests/CommentsManagementTests.cs
Toz.Dotnet/Toz.Dotnet.Tests/Tests/HelpersManagementTests.cs
Toz.Dotnet/Toz.Dotnet.Tests/Tests/HotToHelpInfoManagementTests.cs
Toz.Dotnet/Toz.Dotnet.Tests/Tests/NewsManagmentTest.cs
Toz.Dotnet/Toz.Dotnet.Tests/Tests/OrganizationInfoManagementTest.cs
Toz.Dotnet/Toz.Dotnet.Tests/Tests/PetsManagmentTest.cs
Toz.Dotnet/Toz.Dotnet.Tests/Tests/PetsStatusManagementTest.cs
Toz.Dotnet/Toz.Dotnet.Tests/Tests/ProposalsManagementTests.cs
Toz.Dotnet/Toz.Dotnet.Tests/Tests/UsersManagementTests.cs
Toz.Dotnet/Toz.Dotnet/Controllers/AccountController.cs
Toz.Dotnet/Toz.Dotnet/Resources/Views/Account/ForgotPassword.pl.resx
Toz.Dotnet/Toz.Dotnet/Startup.cs
Toz.Dotnet/Toz.Dotnet/Toz.Dotnet.csproj
Toz.Dotnet/Toz.Dotnet/Views/Account/ForgotPassword.cshtml
Toz.Dotnet/Toz.Dotnet/Views/Account/SignIn.cshtml
Toz.Dotnet/Toz.Dotnet/appsettings.json

If admin forget password then he can send reset token to his email.

Forgot Password
